// <auto-generated />
namespace Emsys.DataAccesLayer.Core
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AgregoCamposAlLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregoCamposAlLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201611020053057_AgregoCamposAlLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
