//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.ServicioExterno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioExterno.ServiciosSoap")]
    public interface ServiciosSoap {
        
        // CODEGEN: Generating message contract since element name param1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Servicio1", ReplyAction="*")]
        Servicios.ServicioExterno.Servicio1Response Servicio1(Servicios.ServicioExterno.Servicio1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Servicio1", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicios.ServicioExterno.Servicio1Response> Servicio1Async(Servicios.ServicioExterno.Servicio1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Servicio1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Servicio1", Namespace="http://tempuri.org/", Order=0)]
        public Servicios.ServicioExterno.Servicio1RequestBody Body;
        
        public Servicio1Request() {
        }
        
        public Servicio1Request(Servicios.ServicioExterno.Servicio1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Servicio1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string param3;
        
        public Servicio1RequestBody() {
        }
        
        public Servicio1RequestBody(string param1, string param2, string param3) {
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Servicio1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Servicio1Response", Namespace="http://tempuri.org/", Order=0)]
        public Servicios.ServicioExterno.Servicio1ResponseBody Body;
        
        public Servicio1Response() {
        }
        
        public Servicio1Response(Servicios.ServicioExterno.Servicio1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Servicio1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Servicios.ServicioExterno.ArrayOfString[] Servicio1Result;
        
        public Servicio1ResponseBody() {
        }
        
        public Servicio1ResponseBody(Servicios.ServicioExterno.ArrayOfString[] Servicio1Result) {
            this.Servicio1Result = Servicio1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapChannel : Servicios.ServicioExterno.ServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapClient : System.ServiceModel.ClientBase<Servicios.ServicioExterno.ServiciosSoap>, Servicios.ServicioExterno.ServiciosSoap {
        
        public ServiciosSoapClient() {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicios.ServicioExterno.Servicio1Response Servicios.ServicioExterno.ServiciosSoap.Servicio1(Servicios.ServicioExterno.Servicio1Request request) {
            return base.Channel.Servicio1(request);
        }
        
        public Servicios.ServicioExterno.ArrayOfString[] Servicio1(string param1, string param2, string param3) {
            Servicios.ServicioExterno.Servicio1Request inValue = new Servicios.ServicioExterno.Servicio1Request();
            inValue.Body = new Servicios.ServicioExterno.Servicio1RequestBody();
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            Servicios.ServicioExterno.Servicio1Response retVal = ((Servicios.ServicioExterno.ServiciosSoap)(this)).Servicio1(inValue);
            return retVal.Body.Servicio1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicios.ServicioExterno.Servicio1Response> Servicios.ServicioExterno.ServiciosSoap.Servicio1Async(Servicios.ServicioExterno.Servicio1Request request) {
            return base.Channel.Servicio1Async(request);
        }
        
        public System.Threading.Tasks.Task<Servicios.ServicioExterno.Servicio1Response> Servicio1Async(string param1, string param2, string param3) {
            Servicios.ServicioExterno.Servicio1Request inValue = new Servicios.ServicioExterno.Servicio1Request();
            inValue.Body = new Servicios.ServicioExterno.Servicio1RequestBody();
            inValue.Body.param1 = param1;
            inValue.Body.param2 = param2;
            inValue.Body.param3 = param3;
            return ((Servicios.ServicioExterno.ServiciosSoap)(this)).Servicio1Async(inValue);
        }
    }
}
