//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.NotificacionAnalysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenShotDatos
    {
        public int Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long cantidadEnviosExitosos { get; set; }
        public long cantidadEnviosReales { get; set; }
        public long cantidadEnviosError { get; set; }
        public double tiempoMaximoEsperaNotificacion { get; set; }
        public double tiempoMinimoEsperaNotificacion { get; set; }
        public double tiempoPromedioEnvioNotificacion { get; set; }
        public int nivelRecursion { get; set; }
        public double duracionRafaga { get; set; }
        public int cantidadTopics { get; set; }
        public int cantidadCodigosNotificaciones { get; set; }
    }
}
